export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_PENDING = "FETCH_TASKS_PENDING";
export const FETCH_TASKS_FULFILLED = "FETCH_TASKS_FULFILLED";
export const FETCH_TASKS_REJECTED = "FETCH_TASKS_REJECTED";
export const FETCH_TASKS_CANCEL = "FETCH_TASKS_CANCEL";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_PENDING = "CREATE_TASK_PENDING";
export const CREATE_TASK_FULFILLED = "CREATE_TASK_FULFILLED";
export const CREATE_TASK_REJECTED = "CREATE_TASK_REJECTED";

export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_PENDING = "DELETE_TASK_PENDING";
export const DELETE_TASK_FULFILLED = "DELETE_TASK_FULFILLED";
export const DELETE_TASK_REJECTED = "DELETE_TASK_REJECTED";
